// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAgents():Promise<Array<main.AgentConfig>>;

export function GetQuestions():Promise<Array<string>>;

export function GetTitle():Promise<string>;
