// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AppConfig>;

export function GetQuestions():Promise<Array<string>>;

export function GetTitle():Promise<string>;
