// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetQuestions() {
  return window['go']['main']['App']['GetQuestions']();
}

export function GetTitle() {
  return window['go']['main']['App']['GetTitle']();
}
